spring:
  datasource:
    url: jdbc:h2:mem:maindb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
